import AppKit
import Combine

struct ClipEntry: Identifiable, Codable, Equatable {
    let id: UUID
    var text: String
    var date: Date
    var pinned: Bool

    init(id: UUID = UUID(), text: String, date: Date = Date(), pinned: Bool = false) {
        self.id = id
        self.text = text
        self.date = date
        self.pinned = pinned
    }
}

/// Watches the general pasteboard and keeps a searchable, pinnable text history.
/// It only watches while the Clipboard module is on and not paused, never
/// records copies marked private, and forgets unpinned items after the
/// retention period.
final class ClipboardManager: ObservableObject {
    @Published private(set) var entries: [ClipEntry] = []
    @Published var search: String = ""

    private let settings: SettingsStore
    private var timer: Timer?
    private var housekeeping: Timer?
    private var cancellables = Set<AnyCancellable>()
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private let defaultsKey = "clipboardHistory"

    /// Set true while *we* write to the pasteboard, so we don't re-capture our own copy.
    private var suppressNextCapture = false

    /// Marks apps put on copies that shouldn't be kept: passwords, one-time
    /// codes, generated content (see nspasteboard.org). Older password
    /// managers use their own markers.
    static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]

    /// Copies made while one of these is frontmost are never recorded, marked or not.
    static let passwordManagers: Set<String> = [
        "com.apple.Passwords",
        "com.apple.keychainaccess",
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.lastpass.LastPass",
        "com.dashlane.dashlanephonefinal",
        "com.proton.pass.electron",
    ]

    init(settings: SettingsStore) {
        self.settings = settings
        load()
        prune()
    }

    /// Follows the settings from here on: watching starts and stops with the
    /// module and the pause switch, and limits apply as they change.
    func start() {
        settings.$enabledModules.map { $0.contains(.clipboard) }
            .combineLatest(settings.$clipboardPaused)
            .map { enabled, paused in enabled && !paused }
            .removeDuplicates()
            .receive(on: RunLoop.main)
            .sink { [weak self] watching in self?.setWatching(watching) }
            .store(in: &cancellables)
        settings.$clipboardLimit.dropFirst().receive(on: RunLoop.main)
            .sink { [weak self] _ in self?.trim(); self?.save() }
            .store(in: &cancellables)
        settings.$clipboardRetentionDays.dropFirst().receive(on: RunLoop.main)
            .sink { [weak self] _ in self?.prune() }
            .store(in: &cancellables)
        housekeeping = Timer.scheduledTimer(withTimeInterval: 15 * 60, repeats: true) { [weak self] _ in
            self?.prune()
        }
    }

    private func setWatching(_ watching: Bool) {
        timer?.invalidate()
        timer = nil
        guard watching else { return }
        // Whatever was copied while off or paused stays unrecorded.
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    var visibleEntries: [ClipEntry] {
        let sorted = entries.sorted { a, b in
            if a.pinned != b.pinned { return a.pinned && !b.pinned }
            return a.date > b.date
        }
        guard !search.isEmpty else { return sorted }
        return sorted.filter { $0.text.localizedCaseInsensitiveContains(search) }
    }

    // MARK: - Polling

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        if suppressNextCapture { suppressNextCapture = false; return }
        guard !Self.isPrivate(types: pb.types ?? [],
                              frontmostApp: NSWorkspace.shared.frontmostApplication?.bundleIdentifier)
        else { return }
        guard let text = pb.string(forType: .string) else { return }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        capture(text)
    }

    static func isPrivate(types: [NSPasteboard.PasteboardType], frontmostApp: String?) -> Bool {
        if let frontmostApp, passwordManagers.contains(frontmostApp) { return true }
        return types.contains { privateTypes.contains($0.rawValue) }
    }

    private func capture(_ text: String) {
        // Move an existing identical entry to the top instead of duplicating.
        if let idx = entries.firstIndex(where: { $0.text == text }) {
            entries[idx].date = Date()
        } else {
            entries.insert(ClipEntry(text: text), at: 0)
        }
        trim()
        save()
    }

    // MARK: - Actions

    func copy(_ entry: ClipEntry) {
        suppressNextCapture = true
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(entry.text, forType: .string)
        lastChangeCount = pb.changeCount
        // Bump recency.
        if let idx = entries.firstIndex(where: { $0.id == entry.id }) {
            entries[idx].date = Date()
            save()
        }
    }

    func togglePin(_ entry: ClipEntry) {
        guard let idx = entries.firstIndex(where: { $0.id == entry.id }) else { return }
        entries[idx].pinned.toggle()
        save()
    }

    func delete(_ entry: ClipEntry) {
        entries.removeAll { $0.id == entry.id }
        save()
    }

    func clearUnpinned() {
        entries.removeAll { !$0.pinned }
        save()
    }

    /// Everything, pinned items included, and the stored copy with it.
    func deleteAll() {
        entries.removeAll()
        UserDefaults.standard.removeObject(forKey: defaultsKey)
    }

    // MARK: - Housekeeping

    private func trim() {
        // Never drop pinned entries; cap the unpinned tail.
        let limit = max(5, settings.clipboardLimit)
        let pinned = entries.filter { $0.pinned }
        var unpinned = entries.filter { !$0.pinned }.sorted { $0.date > $1.date }
        if unpinned.count > limit {
            unpinned = Array(unpinned.prefix(limit))
        }
        entries = pinned + unpinned
    }

    /// Forgets unpinned items older than the retention period.
    private func prune() {
        let days = settings.clipboardRetentionDays
        guard days > 0 else { return }
        let cutoff = Date().addingTimeInterval(-Double(days) * 86_400)
        let before = entries.count
        entries.removeAll { !$0.pinned && $0.date < cutoff }
        if entries.count != before { save() }
    }

    private func save() {
        if let data = try? JSONEncoder().encode(entries) {
            UserDefaults.standard.set(data, forKey: defaultsKey)
        }
    }

    private func load() {
        guard let data = UserDefaults.standard.data(forKey: defaultsKey),
              let decoded = try? JSONDecoder().decode([ClipEntry].self, from: data) else { return }
        entries = decoded
    }
}
